<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-AIprogramming/blob/main/221121AIP10_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###넘파이 배열의 type과 shape
array함수:
type함수:
shape함수:

In [ ]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])

print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


###ndim:배열의 차원크기
###dtype:데이터 형(정수, 실수,...)정보

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


##데이터 형 변환
astype함수: 넘파이 배열의 데이터 형을 변환

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


##넘파이 배열 생성
arrange함수:

zeros,ones함수:


In [ ]:
#넘파이 배열 생성: arange함수 사용 예제
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
#넘파이 배열 생성: zeros함수 사용 예제
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)
#넘파이 배열 생성: ones함수 사용 예제
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


##배열크기 변경/
reshape함수:배열을 지정된 크기로 변경

In [ ]:
#reshape함수사용 예제
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape함수를 잘못 사용한 예: 10개의 요소를 갖는 1차원 배열 array1d,f (4,3)크기의 2차원 배열로 변경 불가

In [ ]:
#reshape함수를 잘못 사용한 예
array1.reshape(4,3)

ValueError: ignored

배열크기변경/
크기지정 시 -1로 지정된 차원의 요소개수를 자동 계산

In [ ]:
array1=np.arange(10)
print(array1)

array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
#오류발생
array1=np.arange(10)
array4=array1.reshape(-1,4)#사이즈가 달라서 오류발생

ValueError: ignored

###넘파이 배열을 리스트로 변환
tolist함수: 넘파이 배열을 리스트로 변환

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원의 nparray를 2차원ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 nparray를 2차원 nparray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


###단일 값 추출(인덱싱)
[k]:k인덱스에 대응되는 배열의 값을 추출, 음수는 뒤에서부터 인덱싱

In [ ]:
#1에서부터 9까지의 1차원 ndarray생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터 값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


###단일값 변경


In [ ]:
#단일값 변경 및 2차원 배열 인덱싱
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


###여러값 추출(슬라이싱)
[시작:끝]의 형태로 슬라이싱

In [ ]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


###2ㅊ원 배열 슬라이싱
[시작0:끝0,시작1:끝1]형태로 슬라이싱

In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[[1:3,:])
print('array2d[:,:]\n',array2d[[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

SyntaxError: ignored

###Boolean인덱싱
True인 인덱스에 대응되는 값을 추출

In [ ]:
array1d=np.arange(start=1,stop=10)
#[]안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


###정렬
sort함수: 배열을 오름차순으로 정렬

In [ ]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬',org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort()호출 후 반환된 행렬:',sort_array2)
print('org_array.sort()호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
org_array.sort()호출 후 반환된 행렬: None
org_array.sort()호출 후 원본 행렬: [1 3 5 9]


In [ ]:
#sort 함수 활용
sort_array1_desc=np.sort(org_array)[::-1]

In [ ]:

##연습문제
a=np.arange(30)
a[0]=30

for i in a:
    if i%3==0:
        print(i)
    if i%7==0:
        print(i)

30
3
6
7
9
12
14
15
18
21
21
24
27
28


In [ ]:
A=np.array([[3,7,2],[8,0,5],[1,6,4]])
A.reshape(9)
B=np.sort(A.reshape(9))[::-1]
B.reshape(3,3)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
A=[[1,2,3],[4,5,6],[10,11,12]]
A.append([7,8,9])
A.sort()
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
